// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU0A5G0DUkPaa-pXk_HzBZtkV0rpuz-sc',
    appId: '1:982110038457:web:a740b3e4cce2c3043aae68',
    messagingSenderId: '982110038457',
    projectId: 'smart-budget-13198',
    authDomain: 'smart-budget-13198.firebaseapp.com',
    storageBucket: 'smart-budget-13198.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTWLHFupc55T9Jeu0rsBNSOt8koQdkKs4',
    appId: '1:982110038457:android:7ee53d11544f5e363aae68',
    messagingSenderId: '982110038457',
    projectId: 'smart-budget-13198',
    storageBucket: 'smart-budget-13198.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtgt8qAIJdkZWya1Gbtbf_pGxinGWfYTA',
    appId: '1:982110038457:ios:89a7bbf1e8a38d4d3aae68',
    messagingSenderId: '982110038457',
    projectId: 'smart-budget-13198',
    storageBucket: 'smart-budget-13198.firebasestorage.app',
    iosBundleId: 'com.example.smartBudget',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtgt8qAIJdkZWya1Gbtbf_pGxinGWfYTA',
    appId: '1:982110038457:ios:89a7bbf1e8a38d4d3aae68',
    messagingSenderId: '982110038457',
    projectId: 'smart-budget-13198',
    storageBucket: 'smart-budget-13198.firebasestorage.app',
    iosBundleId: 'com.example.smartBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU0A5G0DUkPaa-pXk_HzBZtkV0rpuz-sc',
    appId: '1:982110038457:web:d5163dca177890fd3aae68',
    messagingSenderId: '982110038457',
    projectId: 'smart-budget-13198',
    authDomain: 'smart-budget-13198.firebaseapp.com',
    storageBucket: 'smart-budget-13198.firebasestorage.app',
  );
}
